import './globals.css'
import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-900">
        <nav className="flex justify-between px-8 pt-8">
          <Link href="/" className="text-zinc-400 text-sm">Fig Social</Link>
          <Link href="/connect" className="text-zinc-400 text-sm">Connect your Figma Account</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
