import './globals.css'
import Image from "next/image"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-950">
        <nav className="bg-zinc-900 px-8 pt-8">
          <div className="logo text-zinc-400 text-sm">Fig Social</div>
          <Image
            src="/potted_plant.png"
            width={24}
            height={24}
            alt="Picture of the author"
          />
        </nav>
        {children}
      </body>
    </html>
  )
}
